### ISSUE TITLE
Old Versions

### ISSUE THREAD

**Issue by Niko128Flip** [OnixClient-Scripts/OnixClient_Scripts#30]
Hi so I wanted to use Onix when I saw "Onix86: 1.19.21 & 1.19.22 is out and usable if you guys want it" I installed the beta launcher and when I pressed update to the latest version it updated me to 16.40!!!!! and now I don't know how to downgrade. I tried everything but nothing works. + I'm sending it here cuz I have no idea where else to send it

**Comment by Niko128Flip** [comment]
Fixed

**Comment by jqms** [comment]
this is our scripting repo.. how did you even find this?
